[package]
name = "teletel"
version = "0.1.0"
edition = "2021"

[dependencies]
teletel-derive = { path = "derive" }
serial2 = { version = "0.2.28", optional = true }
unidecode = "0.3.0"

[features]
default = ["minitel2"]
minitel1b = []
minitel2 = []
colors = []
serial = ["dep:serial2"]

[[example]]
name = "hello"
required-features = ["serial"]

[[example]]
name = "semigraphic"
required-features = ["serial"]

[[example]]
name = "load_vdt"
required-features = ["serial"]
