[package]
name = "teletel"
version = "0.1.0"
edition = "2021"

[dependencies]
teletel-derive = { path = "derive" }
serialport = { version = "4.7.0", optional = true }
unidecode = "0.3.0"

[features]
serial = ["dep:serialport"]

[[example]]
name = "hello"
required-features = ["serial"]

[[example]]
name = "lumon"
required-features = ["serial"]
