name: Pipeline

on:
    push:
    pull_request:
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    docker:
        name: Docker image
        uses: ./.github/workflows/build.yaml
        permissions:
            contents: read
            packages: write
        secrets: inherit

    ci:
        name: Continuous integration
        runs-on: ubuntu-latest
        needs: [docker]
        timeout-minutes: 15
        container:
            image: ghcr.io/${{ github.repository }}:${{ needs.docker.outputs.tag }}
            credentials:
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

        steps:
            - name: Check out repository code
              uses: actions/checkout@v4

            - name: Extract pre-compiled dependencies
              run: tar -xzf /target-cache.tar.gz

            - name: Lint
              continue-on-error: true
              run: cargo clippy --locked --workspace -- -D warnings

            - name: Audit
              continue-on-error: true
              run: |
                  cargo audit
                  cargo pants

            - name: Build the application
              run: cargo build --locked --workspace

            - name: Run tests
              run: cargo test --locked --workspace
