name: Pipeline

on:
    push:
    pull_request:
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    ci:
        name: Continuous integration
        runs-on: ubuntu-latest

        steps:
            - name: Check out repository code
              uses: actions/checkout@v4

            - name: Install Linux dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install --no-install-recommends libasound2-dev libudev-dev libwayland-dev

            - name: Install Rust toolchain
              uses: dtolnay/rust-toolchain@stable
              with:
                  components: clippy

            - name: Set up Rust cache
              uses: Swatinem/rust-cache@v2
              with:
                  cache-all-crates: "true"
                  cache-directories: |
                      ~/.cargo/advisory-db

            - name: Install cargo-audit
              run: cargo install cargo-audit cargo-pants

            - name: Lint
              continue-on-error: true
              run: cargo clippy -- -D warnings

            - name: Audit
              continue-on-error: true
              run: |
                  cargo audit
                  cargo pants

            - name: Build the application
              run: cargo build

            - name: Run tests
              run: cargo test
